/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CraterRouteImport } from './routes/crater'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TraverseRouteImport } from './routes/traverse'
import { Route as VolumeRouteImport } from './routes/volume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraterRoute = CraterRouteImport.update({
  id: '/crater',
  path: '/crater',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TraverseRoute = TraverseRouteImport.update({
  id: '/traverse',
  path: '/traverse',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeRoute = VolumeRouteImport.update({
  id: '/volume',
  path: '/volume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crater': typeof CraterRoute
  '/landing': typeof LandingRoute
  '/methodology': typeof MethodologyRoute
  '/stats': typeof StatsRoute
  '/traverse': typeof TraverseRoute
  '/volume': typeof VolumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crater': typeof CraterRoute
  '/landing': typeof LandingRoute
  '/methodology': typeof MethodologyRoute
  '/stats': typeof StatsRoute
  '/traverse': typeof TraverseRoute
  '/volume': typeof VolumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crater': typeof CraterRoute
  '/landing': typeof LandingRoute
  '/methodology': typeof MethodologyRoute
  '/stats': typeof StatsRoute
  '/traverse': typeof TraverseRoute
  '/volume': typeof VolumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crater'
    | '/landing'
    | '/methodology'
    | '/stats'
    | '/traverse'
    | '/volume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crater'
    | '/landing'
    | '/methodology'
    | '/stats'
    | '/traverse'
    | '/volume'
  id:
    | '__root__'
    | '/'
    | '/crater'
    | '/landing'
    | '/methodology'
    | '/stats'
    | '/traverse'
    | '/volume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CraterRoute: typeof CraterRoute
  LandingRoute: typeof LandingRoute
  MethodologyRoute: typeof MethodologyRoute
  StatsRoute: typeof StatsRoute
  TraverseRoute: typeof TraverseRoute
  VolumeRoute: typeof VolumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crater': {
      id: '/crater'
      path: '/crater'
      fullPath: '/crater'
      preLoaderRoute: typeof CraterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traverse': {
      id: '/traverse'
      path: '/traverse'
      fullPath: '/traverse'
      preLoaderRoute: typeof TraverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume': {
      id: '/volume'
      path: '/volume'
      fullPath: '/volume'
      preLoaderRoute: typeof VolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CraterRoute: CraterRoute,
  LandingRoute: LandingRoute,
  MethodologyRoute: MethodologyRoute,
  StatsRoute: StatsRoute,
  TraverseRoute: TraverseRoute,
  VolumeRoute: VolumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
